### ISSUE TITLE
Python error when attempting to log in

### ISSUE THREAD

**Issue by gadg3ts** [AdaptiveScale/lxdui#293]
This is a fresh install on an ubuntu 18.04  machine that was already running zfs/lxd
Installed globally as per the instructions.

# snap --version
snap    2.42.5
snapd   2.42.5
series  16
ubuntu  18.04
kernel  4.15.0-74-generic
# lxd --version
3.19

# sudo lxdui start
LXDUI ver. 2.1.2 -- (c)AdaptiveScale, Inc.
http://www.adaptivescale.com
LXDUI started. Running on http://0.0.0.0:15151
PID=3055, Press CTRL+C to quit
[2020-02-01 15:14:31,713] ERROR in app: Exception on /api/user/login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/Flask_JWT-0.3.2-py3.6.egg/flask_jwt/__init__.py", line 126, in _default_auth_request_handler
    return _jwt.auth_response_callback(access_token, identity)
  File "/usr/local/lib/python3.6/dist-packages/Flask_JWT-0.3.2-py3.6.egg/flask_jwt/__init__.py", line 132, in _default_auth_response_handler
    return jsonify({'access_token': access_token.decode('utf-8')})
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/usr/local/lib/python3.6/dist-packages/Werkzeug-1.0.0rc1-py3.6.egg/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'

**Comment by corinroyal** [comment]
I tried installing per instructions today on Ubuntu 18.04 and got the same error on login. I'm happy to help get this resolved if I can.  

[2020-02-01 16:27:04,245] ERROR in app: Exception on /api/user/login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/Flask_JWT-0.3.2-py3.6.egg/flask_jwt/__init__.py", line 126, in _default_auth_request_handler
    return _jwt.auth_response_callback(access_token, identity)
  File "/usr/local/lib/python3.6/dist-packages/Flask_JWT-0.3.2-py3.6.egg/flask_jwt/__init__.py", line 132, in _default_auth_response_handler
    return jsonify({'access_token': access_token.decode('utf-8')})
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/usr/local/lib/python3.6/dist-packages/Werkzeug-1.0.0rc1-py3.6.egg/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'

**Comment by Roundaround** [comment]
+1 for this error

Fresh install:
* Ubuntu Server 18.04.4 LTS
* LXD 3.20
* LXDUI 2.1.2
* Python 3.6.9

Error printout on attempted login (in code block for easier reading):

``` shell
[2020-02-07 15:30:22,281] ERROR in app: Exception on /api/user/login [POST] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/Flask_JWT-0.3.2-py3.6.egg/flask_jwt/__init__.py", line 126, in _default_auth_request_handler
    return _jwt.auth_response_callback(access_token, identity)
  File "/usr/local/lib/python3.6/dist-packages/Flask_JWT-0.3.2-py3.6.egg/flask_jwt/__init__.py", line 132, in _default_auth_response_handler
    return jsonify({'access_token': access_token.decode('utf-8')})
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/usr/local/lib/python3.6/dist-packages/Werkzeug-1.0.0-py3.6.egg/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
```

**Comment by theredkoala21** [comment]
An forced update of Flask seemed to fix the issue.

`pip3 install --upgrade --force-reinstall flask`

**Comment by gadg3ts** [comment]
> A forced update of Flask seemed to fix the issue.
> 
> `pip3 install --upgrade --force-reinstall flask`

If I do that I get other errors from those libraries that are now too new(!?)

$ sudo -H pip3 install --upgrade --force-reinstall flask
Collecting flask
  Downloading Flask-1.1.1-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 1.5 MB/s 
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.0-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 3.0 MB/s 
Collecting click>=5.1
  Downloading Click-7.0-py2.py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 2.8 MB/s 
Collecting Jinja2>=2.10.1
  Downloading Jinja2-2.11.1-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 4.8 MB/s 
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl (27 kB)
**ERROR: lxdui 2.1.2 has requirement Click==6.7, but you'll have click 7.0 which is incompatible.
ERROR: lxdui 2.1.2 has requirement Flask==0.12.2, but you'll have flask 1.1.1 which is incompatible.**
Installing collected packages: itsdangerous, Werkzeug, click, MarkupSafe, Jinja2, flask
  Attempting uninstall: itsdangerous
    Found existing installation: itsdangerous 1.1.0
    Uninstalling itsdangerous-1.1.0:
      Successfully uninstalled itsdangerous-1.1.0
  Attempting uninstall: Werkzeug
    Found existing installation: Werkzeug 1.0.0
    Uninstalling Werkzeug-1.0.0:
      Successfully uninstalled Werkzeug-1.0.0
  Attempting uninstall: click
    Found existing installation: Click 7.0
    Uninstalling Click-7.0:
      Successfully uninstalled Click-7.0
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 1.1.1
    Uninstalling MarkupSafe-1.1.1:
      Successfully uninstalled MarkupSafe-1.1.1
  Attempting uninstall: Jinja2
    Found existing installation: Jinja2 2.11.1
    Uninstalling Jinja2-2.11.1:
      Successfully uninstalled Jinja2-2.11.1
  Attempting uninstall: flask
    Found existing installation: Flask 1.1.1
    Uninstalling Flask-1.1.1:
      Successfully uninstalled Flask-1.1.1
Successfully installed Jinja2-2.11.1 MarkupSafe-1.1.1 Werkzeug-1.0.0 click-7.0 flask-1.1.1 itsdangerous-1.1.0

Then if I downgrade those libs that are too new, that leaves me back where I started...
git pull for lxdui shows it's up to date, so how can we resolve this dependency hell?...

**Comment by gmankono** [comment]
> > A forced update of Flask seemed to fix the issue.
> > `pip3 install --upgrade --force-reinstall flask`
> 
> Then if I downgrade those libs that are too new, that leaves me back where I started...
> git pull for lxdui shows it's up to date, so how can we resolve this dependency hell?...

+1 for this error, and for the issue with a Flask forced update NOT resolving the issue.

Ubuntu 18.04.4 LTS
LXD 3.20
LXDUI 2.1.2
Python 3.6.9

Still getting the error on web login attempt:

[2020-02-15 00:52:31,231] ERROR in app: Exception on /api/user/login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1982, in wsgi_app
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1614, in full_dispatch_request
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1517, in handle_user_exception
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/_compat.py", line 33, in reraise
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1612, in full_dispatch_request
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1598, in dispatch_request
  File "/usr/local/lib/python3.6/dist-packages/Flask_JWT-0.3.2-py3.6.egg/flask_jwt/__init__.py", line 126, in _default_auth_request_handler
    return _jwt.auth_response_callback(access_token, identity)
  File "/usr/local/lib/python3.6/dist-packages/Flask_JWT-0.3.2-py3.6.egg/flask_jwt/__init__.py", line 132, in _default_auth_response_handler
    return jsonify({'access_token': access_token.decode('utf-8')})
  File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/json.py", line 251, in jsonify
  File "/usr/local/lib/python3.6/dist-packages/Werkzeug-1.0.0-py3.6.egg/werkzeug/local.py", line 347, in __getattr__
AttributeError: 'Request' object has no attribute 'is_xhr'

**Comment by kongkrit** [comment]
+1 for this. I am getting the same errors:

**Comment by ShadowMonster** [comment]
Problem is with Werkzeug library which got major upgrade recently:
`pip install --upgrade --force-reinstall Werkzeug==0.16.1`
Should fix that

**Comment by gadg3ts** [comment]
That doesn't really fix the other previously reported issue:
$ sudo -H pip install --upgrade --force-reinstall Werkzeug==0.16.1
Collecting Werkzeug==0.16.1
  Downloading Werkzeug-0.16.1-py2.py3-none-any.whl (327 kB)
     |████████████████████████████████| 327 kB 2.3 MB/s
ERROR: lxdui 2.1.2 has requirement Click==6.7, but you'll have click 7.0
which is incompatible.
ERROR: lxdui 2.1.2 has requirement Flask==0.12.2, but you'll have flask
1.1.1 which is incompatible.
Installing collected packages: Werkzeug
  Attempting uninstall: Werkzeug
    Found existing installation: Werkzeug 1.0.0
    Uninstalling Werkzeug-1.0.0:
      Successfully uninstalled Werkzeug-1.0.0
Successfully installed Werkzeug-0.16.1

**Comment by respadas** [comment]
Hi,

the solution from @ShadowMonster works fine for me.

Regards,

**Comment by Inujel** [comment]
I fixed the problem by adding werkzeug<1.0 to requirements.txt, it seems to work flawlessly now.

**Comment by vhajdari** [comment]
I merged the latest versions of Flask into the main branch so this problem should be solved.
